# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
mylist = np.zeros(10)
mylist

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [3]:
mylist = np.arange(10,49)
mylist

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

4. Find the shape of previous array in question 3

In [4]:
mylist.shape

(39,)

5. Print the type of the previous array in question 3

In [5]:
mylist.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [6]:
print(f"Numpy Version : {np.__version__}")
print(np.show_config())

Numpy Version : 1.19.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


7. Print the dimension of the array in question 3


In [7]:
mylist.ndim

1

8. Create a boolean array with all the True values

In [8]:
myBoolList = np.ones(10,dtype=bool)
myBoolList

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

9. Create a two dimensional array




In [9]:
my2dList = np.array([[1,2,3,4,5,6], [11,22,33,44,55,66]])
my2dList

array([[ 1,  2,  3,  4,  5,  6],
       [11, 22, 33, 44, 55, 66]])

10. Create a three dimensional array



In [10]:
my3dList = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
my3dList

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
mylist = np.arange(10)
np.flipud(mylist)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

12. Create a null vector of size 10 but the fifth value which is 1 

In [12]:
mylist = np.zeros(10)
mylist[4] = 1
mylist

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [13]:
mylist = np.arange(1,10).reshape(3,3)
mylist

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [14]:
arr = np.array([1,2,3,4,5])
#changing data type
arr = arr.astype("float32")
#printing array
arr

array([1., 2., 3., 4., 5.], dtype=float32)

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [15]:
arr1 = np.array([   [1., 2., 3.],
                    [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],
           [7., 2., 12.]])

arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [16]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])

arr3 = arr1==arr2
arr3

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [17]:
arr = np.arange(0,9)
odd_in_arr=arr[arr % 2 != 0]
odd_in_arr

array([1, 3, 5, 7])

18. Replace all odd numbers to -1 from previous array

In [18]:
arr[odd_in_arr] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [19]:
arr = np.arange(10)
arr[5:9] = 12

In [20]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [21]:
arr = np.ones((10,10))
arr[1:-1,1:-1]=0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [22]:
arr2d = np.array([  [1, 2, 3],
                    [4, 5, 6], 
                    [7, 8, 9]
                 ])
arr2d[1][1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [23]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0][0][:]=64
arr3d[0][1][:]=64
arr3d


array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [24]:
arr2d=np.arange(0,9).reshape(3,3)
arr2d[0]

array([0, 1, 2])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [25]:
arr2d=np.arange(0,9).reshape(3,3)
arr2d[1:2,1:2]


array([[4]])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [26]:
arr2d=np.arange(0,9).reshape(3,3)
arr2d[0:2,2:]

array([[2],
       [5]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [27]:
arr = np.random.randint(1000, size=100).reshape(10,10)
arr

array([[170, 998,  76, 337, 602,  68, 209, 926, 422, 116],
       [428,  75, 301, 916, 914, 234,  74, 705, 546, 457],
       [518, 648, 165, 962, 118, 510,  83, 500, 749, 539],
       [472, 641, 980, 100, 267, 560, 811, 676, 674, 816],
       [130, 857, 885, 681, 777, 220, 610, 200,   9, 227],
       [ 18, 352, 983, 728, 403, 215, 375, 523, 131, 315],
       [934,  42, 442, 390, 362, 514, 615, 241, 195, 579],
       [548, 180, 878, 363, 454, 661, 698, 939, 645, 240],
       [582, 267, 536,  93, 592, 751, 948, 409, 584, 455],
       [846, 105, 564, 595, 933, 956, 896, 882, 436,   7]])

In [28]:
np.amin(arr)

7

In [29]:
np.amax(arr)

998

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [30]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
common = np.intersect1d(a,b)
common

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [31]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
position = np.intersect1d(a,b, return_indices=True)
position

(array([2, 4]), array([1, 5], dtype=int64), array([1, 5], dtype=int64))

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [32]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[names != "Will"]

array([[ 0.80827645, -0.68565091,  0.05029441,  0.27956582],
       [-1.1238036 ,  0.01833368,  0.61545698,  0.88738414],
       [-0.02333904,  1.47597515, -0.92946198,  1.35125156],
       [ 0.88163418,  1.31703489, -1.23842078,  2.31415011],
       [ 0.0534663 ,  2.02075755, -2.02204712, -0.73210834]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [44]:
data[names == "Bob"]

array([[ 0.80827645, -0.68565091,  0.05029441,  0.27956582],
       [-0.02333904,  1.47597515, -0.92946198,  1.35125156]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [34]:
d2=np.arange(1,16).reshape(5,3)
d2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [35]:
d3 = np.arange(1,17).reshape(2,2,4)
d3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

In [36]:
np.swapaxes(d3,0,1)

array([[[ 1,  2,  3,  4],
        [ 9, 10, 11, 12]],

       [[ 5,  6,  7,  8],
        [13, 14, 15, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [37]:
ar=np.arange(1,11)
sqrt_ar=np.sqrt(ar)
sqrt_ar[sqrt_ar < 0.5] = 0
sqrt_ar

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [38]:
rndarr1 = np.random.random(12)
rndarr2 = np.random.random(12)
print(rndarr1)
print(rndarr2)
newarr = np.array([np.amin(rndarr1),np.amax(rndarr2)])
print(newarr)


[0.80024749 0.30732779 0.66380925 0.35846187 0.51363359 0.2114768
 0.06457119 0.74132745 0.6749405  0.28031826 0.67018531 0.45402635]
[0.58945167 0.42227658 0.95773374 0.69963246 0.18451298 0.00769091
 0.8112493  0.86501141 0.94762664 0.78848245 0.12647274 0.11619882]
[0.06457119 0.95773374]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [39]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [40]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
a = np.array([i for i in a if i not in b])
a

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [41]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])

sampleArray[:,2] = newColumn

sampleArray


array([[34, 43, 10],
       [82, 22, 10],
       [53, 94, 10]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [42]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [43]:
randArray = np.random.random(20)

np.cumsum(randArray)

array([0.10118955, 0.65867007, 1.60457495, 2.52491509, 2.8436473 ,
       2.86865941, 3.40192832, 4.35504756, 4.5906746 , 5.57255853,
       5.90892548, 6.53101881, 6.7399637 , 7.41152093, 8.12050182,
       8.29718437, 8.82354229, 8.93482176, 9.3265032 , 9.35378097])